version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: psyAssistPlatformFcs
      POSTGRES_USER: psyadmin
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    restart: no

  rabbitmq-manager:
    image: "rabbitmq:3.13-management"
    container_name: 'rabbitmq-manager'
    ports:
      - 5672:5672
      - 15672:15672

  psyassistfeedback.webapi:
    image: ${DOCKER_REGISTRY-}psyassistfeedbackwebapi
    build:
      context: .
      dockerfile: PsyAssistFeedback.WebApi/Dockerfile
